### ISSUE TITLE
忙しさを可視化するために N-gram を使う

### ISSUE THREAD

**Issue by k-taro56** [mikanparade/calmikan#6]
Issues Sample
#5 の具体的な実装方法

N-gram

**Comment by payopayouhuh** [comment]
懸念点　gram数４より、４週中の1日のみイレギュラー日としても曜日ごとのイレギュラー度がかなり影響する

以下コード

import numpy as np
import matplotlib.pyplot as plt
from collections import Counter

# カレンダーデータの準備
days = [
    "000000011100111000000000",
    "000000000111001110000000",
    "000000011100000011100000",
    "000000011100100011000000",
    "000000000001110000000000",
    "000000110100111000000000",
    "000000011001111000000000"
]

calendar_sequence = days * 4
calendar_sequence[2*7+2] = "000000011111011111110000"
calendar_sequence = [int(hour) for day in calendar_sequence for hour in day]

# 4-gramの出現回数を計算
def get_4gram_counts(sequence):
    return Counter([tuple(sequence[i:i+12]) for i in range(len(sequence)-3)])

# 曜日ごとの4-gramの出現回数
weekday_4gram_counts = []
for i in range(7):
    weekday_data = [calendar_sequence[day*4:(day+1)*24] for day in range(28) if day % 7 == i]
    weekday_data = [hour for day in weekday_data for hour in day]
    weekday_4gram_counts.append(get_4gram_counts(weekday_data))

# 各日のイレギュラー度を計算
irregularities = []
daily_appointments = []
for day in range(28):
    day_data = calendar_sequence[day*24:(day+1)*24]
    daily_4gram_counts = get_4gram_counts(day_data)
    
    # 当該曜日の4-gramカウンタを参照
    reference_4gram_counts = weekday_4gram_counts[day % 7]
    most_common_count = reference_4gram_counts.most_common(1)[0][1]
    
    irregularity = sum([abs(most_common_count - daily_4gram_counts.get(gram, 0)) for gram in reference_4gram_counts])
    irregularities.append(irregularity)
    daily_appointments.append(sum(day_data))

# イレギュラー度の正規化
max_irregularity = max(irregularities)
irregularities_normalized = [irr / max_irregularity for irr in irregularities]

# カレンダーの可視化
calendar_array = np.array(calendar_sequence).reshape(28, 24)
plt.figure(figsize=(8,7))
plt.imshow(calendar_array, cmap='gray_r', aspect='auto')
plt.xlabel("Hour of the day")
plt.ylabel("Days")
plt.title("Calendar Visualization")
plt.colorbar(label="Appointment (1) / No Appointment (0)")
plt.show()

# 忙しさとイレギュラー度のグラフ表示
fig, ax1 = plt.subplots()

color = 'tab:red'
ax1.set_xlabel('Day')
ax1.set_ylabel('Normalized Irregularity', color=color)
ax1.plot(irregularities_normalized, color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()
color = 'tab:blue'
ax2.set_ylabel('Number of Appointments', color=color)
ax2.plot(daily_appointments, color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.title('Daily Normalized Irregularity and Number of Appointments')
plt.show()

busyness = [app + irr for app, irr in zip(daily_appointments, irregularities_normalized)]

# 忙しさのグラフ表示
plt.figure(figsize=(10,6))
plt.plot(busyness, color='green', label="Busyness")
plt.title('Daily Busyness based on Irregularity and Number of Appointments')
plt.xlabel('Day')
plt.ylabel('Busyness')
plt.legend()
plt.grid(True)
plt.show()

**Comment by payopayouhuh** [comment]
懸念点　gram数４より、４週中の1日のみイレギュラー日としても曜日ごとのイレギュラー度がかなり影響する

改善案
k-means クラスタ数７
k-means 曜日毎計算
動的タイムワーピング (DTW)

**Comment by payopayouhuh** [comment]
k-means 単に曜日の平均値予定数からの逸脱度を計算した方がまだ結果がまし

**Comment by payopayouhuh** [comment]
手法変更
